"""baseline

Revision ID: 85008e4d00a0
Revises:
Create Date: 2026-08-07 12:55:29.245520

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85008e4d00a0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("reports_on", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "body_measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("waist_cm", sa.Float(), nullable=True),
        sa.Column("chest_cm", sa.Float(), nullable=True),
        sa.Column("hips_cm", sa.Float(), nullable=True),
        sa.Column("thigh_cm", sa.Float(), nullable=True),
        sa.Column("arm_cm", sa.Float(), nullable=True),
        sa.Column("note", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("weight_kg IS NULL OR weight_kg > 0"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("body_measurements", schema=None) as batch_op:
        batch_op.create_index(
            "ix_body_measurements_user_date", ["user_id", "recorded_on"], unique=False
        )

    op.create_table(
        "improvement_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_full_name", sa.Text(), nullable=False),
        sa.Column("request_text", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'new'"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("status IN ('new','done','rejected')"),
        sa.CheckConstraint("length(trim(request_text)) > 0"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("improvement_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_improvement_requests_status_created", ["status", "created_at"], unique=False
        )

    op.create_table(
        "user_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("goal_type", sa.Text(), nullable=False),
        sa.Column("start_weight_kg", sa.Float(), nullable=True),
        sa.Column("target_weight_kg", sa.Float(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("goal_type IN ('lose','gain','maintain','muscle')"),
        sa.CheckConstraint("start_weight_kg IS NULL OR start_weight_kg > 0"),
        sa.CheckConstraint("target_weight_kg IS NULL OR target_weight_kg > 0"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("user_goals", schema=None) as batch_op:
        batch_op.create_index(
            "ux_user_goals_active", ["user_id"], unique=True, sqlite_where=sa.text("is_active = 1")
        )

    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("sex", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint("sex IN ('male','female')"),
        sa.CheckConstraint("height_cm IS NULL OR height_cm > 0"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "workouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("photo_file_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("kind IN ('cardio','strength')"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.create_index("ix_workouts_user_date", ["user_id", "performed_on"], unique=False)

    op.create_table(
        "workout_body_parts",
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("body_part", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workout_id", "body_part"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_body_parts")
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_index("ix_workouts_user_date")

    op.drop_table("workouts")
    op.drop_table("user_profiles")
    with op.batch_alter_table("user_goals", schema=None) as batch_op:
        batch_op.drop_index("ux_user_goals_active", sqlite_where=sa.text("is_active = 1"))

    op.drop_table("user_goals")
    with op.batch_alter_table("improvement_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_improvement_requests_status_created")

    op.drop_table("improvement_requests")
    with op.batch_alter_table("body_measurements", schema=None) as batch_op:
        batch_op.drop_index("ix_body_measurements_user_date")

    op.drop_table("body_measurements")
    op.drop_table("users")
    # ### end Alembic commands ###
